### ISSUE TITLE
Some suggestions for sites

### ISSUE THREAD

**Issue by OshekharO** [KillerDogeEmpire/dsh-extension-reboot#1]
https://github.com/hexated/cloudstream-extensions-hexated/issues/165

https://github.com/koikiss-dev/jimov_api

https://github.com/OshekharO/Web-Indexer/issues/8

**Comment by dontseehereThomas** [comment]
Mfs already creating issues

**Comment by OshekharO** [comment]
Alright mf I am closing 😁.
